export {default as Header} from './header/Header'
export {default as Footer} from './footer/Footer'
export {default as Hero} from './hero/Hero'
export {default as MostPopular} from './mostPopular/MostPopular'
export {default as GamingLibrary} from './GamingLibrary/GamingLibrary'
export {default as FeatturedGames} from './FeatturedGames/FeatturedGames'